application: djangae-scaffold
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: lxml
  version: 2.3.5
- name: PIL
  version: 1.1.7
- name: MySQLdb
  version: 1.2.5

handlers:

- url: /_ah/(mapreduce|queue|warmup|internalupload).*
  script: app.wsgi.application
  login: admin
  secure: always

- url: /static/admin/
  static_dir: sitepackages/django/contrib/admin/static/admin/
  secure: always

# Set Django admin to be login:admin as well as Django's is_staff restriction
- url: /admin.*
  script: app.wsgi.application
  secure: always
  login: admin

- url: /.*
  script: app.wsgi.application
  secure: always

skip_files:
    - manage.py
    - README.md
    - install_deps
    - requirements.txt
    - sitepackages/google_appengine*
    - \.storage.*
    - \.git
    - (.*)\.pyc
